[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "hello"
version = "0.2.0"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
toolbox = "toolbox.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
